openapi: 3.0.3
info:
  version: "0.1.0"
  title: <pyPoll>
      
paths:
  /sign_in:
    get:
      description: |
        Redirects to AWSCognito login webpage
      responses:
        301:
          description: Redirected to login page

  /aws_cognito_redirect:
    get:
      description: |
        Route AWSCognito redirects to after successful login
      responses:
        301:
          description: Redirected to home page
          
  /home:
    get:
      description: |
        Returns home page for the user
      responses:
        200:
          description: Successful rendering of home page

  /viewpoll/{pollTitle}:
    get:
        description: |
          Returns view page for poll
        parameters: 
        - name: polltitle
          in: path
          description: Defines title of requested poll
          required: true
          schema: 
            type: string
        responses:
          200:
            description: | 
              Succesful rendering of poll

  /votePoll/{pollid}:
    get:
        description: |
          Returns view page for poll
        parameters: 
        - name: pollid
          in: path
          description: Defines id of requested poll
          required: true
          schema: 
            type: integer
            format: int64
        responses:
            200:
              description: Succesful rendering of poll voting page
      
  /polls:
    post:
      description: Create a new poll
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
      responses:
        200:
          description: succesfully created the poll
        405:
          description: invalid input
 
          
  /polls/{pollid}:
    get:
      description: |
        Returns requested poll
      parameters:
        - name: pollid
          in: path
          description: Defines pollid of requested poll
          required: true
          schema: 
            type: integer
            format: int64
      responses:
        200:
          description: Succesfully returned poll
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
        404:
          description: poll not found
    
  /polls/{pollid}/vote:
    post:
      description: Insert vote for poll in selected choice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Choice'
      responses:
        200:
          description: succesfully voted in poll
        405:
          description: invalid input
                         
                    
                    
components:             
  schemas:         
    Choice:
      type: object
      properties:
        choice_id:
          type: integer
          example: 5
        choice_text:
          type: string
          example: "choice"
        poll_id:
          type: integer
          example: 10
        vote:
          type: integer
          example: 2
    Poll:
        type: object
        properties:
          poll_id:
            type: integer
            example: 10
          title:
            type: string
            example: "Poll title"
          description:
            type: string
            example: "Poll description"
          user_id:
            type: integer
            example: 10
        
          
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              

            
            
            
            
            
            
            
            
          
    
